name: 'Clean Old Releases'
description: 'Cleans old tags and releases'
inputs:
  token:
    description: 'github token from secret'
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'main.js'