name: 'Clean Old Releases'
description: 'Cleans old tags and releases'
inputs:
  token:
    description: 'github token from secret'
    required: true
    default: ''
  age:
    description: 'Maximum age of tags and releases (in months)'
    required: true
    default: 6
runs:
  using: 'node16'
  main: 'main.js'